#:kivy 1.10.1

<PongGame>
    canvas:
        Rectangle:
            pos: self.center_x - 5, 0
            size: 10, self.height

    Label:
        text:"0"
        font_size: 50
        top: root.top -50
        center_x: root.width /4

    Label:
        text:"0"
        font_size: 50
        center_x: root. width * 3/4
        top: root.top -50

<PongBall>
    size: 40,40
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size


